name: Release
on:
  push:
    branches:
      - main
      - "*[0-9].*[0-9].x"
      - "*[0-9].x.x"
      - dev
      - alpha
      - beta
  # workflow_dispatch makes it possible to trigger the run manually
  workflow_dispatch:

jobs:
  semantic-release:
    name: Run Semantic Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@16ca923e6ccbb50770c415a0ccd43709a8c5f7a4 # v4.2.2
      with:
        semantic_version: 24.2.6
        extra_plugins: |
          conventional-changelog-conventionalcommits@9.1.0
          semantic-release-major-tag@0.3.2
      env:
        GITHUB_TOKEN: ${{ secrets.CREATE_RELEASE }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
